import Erdos279.AnalyticConstants

/-!
# Arithmetic hypotheses for the controller indicator

The multiplicative function used in Section 2 is the characteristic
function of the semigroup generated by primes `1 mod h`.  This file proves
its prime values, residue-class periodicity, and uniform `0/1` bound.  These
are the function-side hypotheses of the cited Fouvry--Tenenbaum and
Selberg--Delange theorems.
-/

namespace Erdos279

/-- A prime itself belongs to the controller semigroup exactly in the target progression. -/
theorem controllerSemigroup_prime_iff
    {h q : Prime} :
    ControllerSemigroup h q.1 ↔ InControllerProgression h q := by
  constructor
  · intro hq
    exact hq.primeDivisor_mem (Nat.dvd_refl q.1)
  · intro hq
    simpa using
      ControllerSemigroup.mul q hq (ControllerSemigroup.one (h := h))

/-- Exact value of the controller indicator at a project prime. -/
theorem controllerIndicator_prime_eq_one_iff
    {h q : Prime} :
    controllerIndicator h q.1 = 1 ↔
      InControllerProgression h q := by
  rw [controllerIndicator_eq_one_iff,
    controllerSemigroup_prime_iff]

/-- Exact value at a mathlib natural prime. -/
theorem controllerIndicator_natPrime
    (h : Prime) {p : Nat} (hp : p.Prime) :
    controllerIndicator h p =
      if p % h.1 = 1 then 1 else 0 := by
  let q : Prime :=
    ⟨p, (isPrime_iff_natPrime p).mpr hp⟩
  by_cases hprogression : p % h.1 = 1
  · have hq : InControllerProgression h q := hprogression
    have hmem : ControllerSemigroup h p := by
      simpa [q] using
        (controllerSemigroup_prime_iff (h := h) (q := q)).mpr hq
    rw [controllerIndicator_apply_of_mem hmem]
    simp [hprogression]
  · have hq : ¬InControllerProgression h q := hprogression
    have hnot : ¬ControllerSemigroup h p := by
      simpa [q] using
        (not_congr controllerSemigroup_prime_iff).mpr hq
    simp [hprogression, controllerIndicator_apply_of_not_mem hnot]

/--
On primes, the indicator depends only on the residue class modulo `h`.
-/
theorem controllerIndicator_prime_residue_periodic
    (h : Prime) {p q : Nat}
    (hp : p.Prime) (hq : q.Prime)
    (hpq : p % h.1 = q % h.1) :
    controllerIndicator h p = controllerIndicator h q := by
  rw [controllerIndicator_natPrime h hp,
    controllerIndicator_natPrime h hq, hpq]

/-- Every controller-indicator value is either zero or one. -/
theorem controllerIndicator_eq_zero_or_one
    (h : Prime) (n : Nat) :
    controllerIndicator h n = 0 ∨
      controllerIndicator h n = 1 := by
  classical
  by_cases hn : ControllerSemigroup h n
  · exact Or.inr (controllerIndicator_apply_of_mem hn)
  · exact Or.inl (controllerIndicator_apply_of_not_mem hn)

/-- Uniform natural-number bound `f(n) ≤ 1`. -/
theorem controllerIndicator_le_one
    (h : Prime) (n : Nat) :
    controllerIndicator h n ≤ 1 := by
  rcases controllerIndicator_eq_zero_or_one h n with hn | hn <;>
    simp [hn]

/-- Uniform real absolute-value bound `|f(n)| ≤ 1`. -/
theorem abs_controllerIndicator_cast_le_one
    (h : Prime) (n : Nat) :
    |((controllerIndicator h n : Nat) : Real)| ≤ 1 := by
  have hn := controllerIndicator_le_one h n
  rw [abs_of_nonneg (by positivity)]
  exact_mod_cast hn

/-- The real-valued controller indicator is nonnegative. -/
theorem controllerIndicator_cast_nonneg
    (h : Prime) (n : Nat) :
    0 ≤ ((controllerIndicator h n : Nat) : Real) := by
  positivity

/-- Complete multiplicativity after coercion to `ℝ`. -/
theorem controllerIndicator_cast_mul
    (h : Prime) (m n : Nat) :
    ((controllerIndicator h (m * n) : Nat) : Real) =
      ((controllerIndicator h m : Nat) : Real) *
        ((controllerIndicator h n : Nat) : Real) := by
  rw [controllerIndicator_mul]
  norm_cast

end Erdos279
