import Erdos279.Completion

/-!
# The controller-prime semigroup

This is the algebraic part of Case 1.  It does not use unique factorization:
membership is recorded by an inductive generation certificate.
-/

namespace Erdos279

theorem Prime.one_lt (p : Prime) : 1 < p.1 :=
  Nat.lt_of_lt_of_le Nat.one_lt_two p.two_le

/-- The multiplicative semigroup generated by primes `p ≡ 1 (mod h)`. -/
inductive ControllerSemigroup (h : Prime) : Nat → Prop
  | one : ControllerSemigroup h 1
  | mul (p : Prime) {u : Nat} :
      InControllerProgression h p →
      ControllerSemigroup h u →
      ControllerSemigroup h (p.1 * u)

theorem ControllerSemigroup.mod_h_eq_one
    {h : Prime} {u : Nat} (hu : ControllerSemigroup h u) :
    u % h.1 = 1 := by
  induction hu with
  | one =>
      exact Nat.mod_eq_of_lt h.one_lt
  | mul p hp hu ih =>
      rw [Nat.mul_mod, hp, ih]
      simp [Nat.mod_eq_of_lt h.one_lt]

/--
The permanent hub class `a_h=1` covers every controller-smooth target once
the hub is mature.
-/
theorem controllerSemigroup_covered_by_hub
    {k u : Nat} {h : Prime} {a : ShiftedAssignment}
    (hu : ControllerSemigroup h u)
    (ha : (a h : Nat) = 1)
    (hmature : k * h.1 ≤ u + 1) :
    ShiftedMatureCovers k u a := by
  refine ⟨h, hmature, ?_⟩
  rw [hu.mod_h_eq_one, ha]

/-- The hard multiplicative form `h^e u` with `e ≥ 1`. -/
def HasHardForm (h : Prime) (m : Nat) : Prop :=
  ∃ e u : Nat, 1 ≤ e ∧
    ControllerSemigroup h u ∧
    m = h.1 ^ e * u

end Erdos279
