import Erdos279.Factorization

/-!
Elementary bridges between prime-factor smoothness, the controller
semigroup, and the explicit hard-target form.

The positive hard-form theorem needs `0 < m`.  Without it the unqualified
statement is false: for hub `2`, the number `0` is smooth and divisible by
`2`, but cannot equal `2^e * u` with `e ≥ 1` and positive semigroup `u`.
-/

namespace Erdos279

/--
If every prime divisor of `m` is either the hub or a controller prime, and
the hub does not divide `m`, then `m` belongs to the controller semigroup.
-/
theorem smoothFor_controllerSemigroup_of_not_dvd
    {h : Prime} {m : Nat}
    (hsmooth : SmoothFor h m)
    (hnotHub : ¬ h.1 ∣ m) :
    ControllerSemigroup h m := by
  induction m using Nat.strongRecOn with
  | ind m ih =>
      have hmpos : 0 < m := by
        apply Nat.pos_of_ne_zero
        intro hmzero
        apply hnotHub
        rw [hmzero]
        exact Nat.dvd_zero h.1
      by_cases hmone : m = 1
      · simpa [hmone] using ControllerSemigroup.one (h := h)
      · have hmgt : 1 < m := by omega
        rcases exists_isPrime_dvd hmgt with ⟨q, hqm⟩
        have hqG : InControllerProgression h q := by
          rcases hsmooth q hqm with hqh | hqG
          · exfalso
            apply hnotHub
            simpa [hqh] using hqm
          · exact hqG
        let u : Nat := m / q.1
        have hqu : q.1 * u = m := by
          exact Nat.mul_div_cancel' hqm
        have hult : u < m := by
          dsimp [u]
          exact Nat.div_lt_self hmpos q.one_lt
        have hudivm : u ∣ m := by
          rw [← hqu]
          exact Nat.dvd_mul_left u q.1
        have husmooth : SmoothFor h u := by
          intro r hru
          exact hsmooth r (Nat.dvd_trans hru hudivm)
        have hunotHub : ¬ h.1 ∣ u := by
          intro hhu
          exact hnotHub (Nat.dvd_trans hhu hudivm)
        have huSemigroup : ControllerSemigroup h u :=
          ih u hult husmooth hunotHub
        rw [← hqu]
        exact ControllerSemigroup.mul q hqG huSemigroup

/-- Every prime divisor of a controller-semigroup element is a controller prime. -/
theorem ControllerSemigroup.primeDivisor_mem
    {h q : Prime} {u : Nat}
    (hu : ControllerSemigroup h u)
    (hqu : q.1 ∣ u) :
    InControllerProgression h q := by
  induction hu with
  | one =>
      have hqone : q.1 = 1 := Nat.dvd_one.mp hqu
      have hq2 := q.two_le
      omega
  | mul p hp hu ih =>
      rcases isPrime_dvd_mul q.2 hqu with hqp | hqu'
      · have hEq : q = p :=
          prime_dvd_prime_eq (p := q) (q := p) hqp
        simpa [hEq] using hp
      · exact ih hqu'

/-- An explicit hard form is smooth for the hub. -/
theorem HasHardForm.smoothFor
    {h : Prime} {m : Nat}
    (hm : HasHardForm h m) :
    SmoothFor h m := by
  rcases hm with ⟨e, u, _he, hu, rfl⟩
  intro q hq
  rcases isPrime_dvd_mul q.2 hq with hqpow | hqu
  · left
    exact prime_dvd_prime_eq
      (p := q) (q := h) (isPrime_dvd_pow q.2 hqpow)
  · right
    exact hu.primeDivisor_mem hqu

/-- Every explicit hard form is divisible by the hub. -/
theorem HasHardForm.hub_dvd
    {h : Prime} {m : Nat}
    (hm : HasHardForm h m) :
    h.1 ∣ m := by
  rcases hm with ⟨e, u, he, _hu, rfl⟩
  cases e with
  | zero =>
      omega
  | succ e =>
      refine ⟨h.1 ^ e * u, ?_⟩
      simp [Nat.pow_succ, Nat.mul_comm, Nat.mul_left_comm]

/-- Every explicit hard form is positive. -/
theorem HasHardForm.pos
    {h : Prime} {m : Nat}
    (hm : HasHardForm h m) :
    0 < m := by
  rcases hm with ⟨e, u, _he, hu, rfl⟩
  exact Nat.mul_pos (Nat.pow_pos h.pos) hu.pos

/-- Explicit hard form implies the prime-factor definition of a hard target. -/
theorem HasHardForm.hardTarget
    {h : Prime} {m : Nat}
    (hm : HasHardForm h m) :
    HardTarget h m :=
  ⟨hm.smoothFor, hm.hub_dvd⟩

/--
Every positive smooth target divisible by the hub has the hard
factorization `h^e u`, where `e ≥ 1` and `u` is generated by controller
primes.
-/
theorem smoothFor_hasHardForm_of_dvd
    {h : Prime} {m : Nat}
    (hmpos : 0 < m)
    (hsmooth : SmoothFor h m)
    (hhub : h.1 ∣ m) :
    HasHardForm h m := by
  induction m using Nat.strongRecOn with
  | ind m ih =>
      let v : Nat := m / h.1
      have hhv : h.1 * v = m := by
        exact Nat.mul_div_cancel' hhub
      have hhle : h.1 ≤ m := Nat.le_of_dvd hmpos hhub
      have hvpos : 0 < v := by
        dsimp [v]
        exact Nat.div_pos hhle h.pos
      have hvlt : v < m := by
        dsimp [v]
        exact Nat.div_lt_self hmpos h.one_lt
      have hvdivm : v ∣ m := by
        rw [← hhv]
        exact Nat.dvd_mul_left v h.1
      have hvsmooth : SmoothFor h v := by
        intro q hqv
        exact hsmooth q (Nat.dvd_trans hqv hvdivm)
      by_cases hhubv : h.1 ∣ v
      · rcases ih v hvlt hvpos hvsmooth hhubv with
          ⟨e, u, he, hu, hveq⟩
        refine ⟨e + 1, u, ?_, hu, ?_⟩
        · omega
        · rw [← hhv, hveq]
          simp [Nat.pow_succ, Nat.mul_comm, Nat.mul_left_comm]
      · have hvSemigroup :
            ControllerSemigroup h v :=
          smoothFor_controllerSemigroup_of_not_dvd hvsmooth hhubv
        refine ⟨1, v, by omega, hvSemigroup, ?_⟩
        simpa using hhv.symm

/-- A positive `HardTarget` has the explicit hard multiplicative form. -/
theorem hardTarget_hasHardForm
    {h : Prime} {m : Nat}
    (hmpos : 0 < m)
    (hm : HardTarget h m) :
    HasHardForm h m :=
  smoothFor_hasHardForm_of_dvd hmpos hm.1 hm.2

/-- On positive targets, the two hard-target definitions are equivalent. -/
theorem positive_hardTarget_iff_hasHardForm
    {h : Prime} {m : Nat}
    (hmpos : 0 < m) :
    HardTarget h m ↔ HasHardForm h m := by
  constructor
  · exact hardTarget_hasHardForm hmpos
  · exact HasHardForm.hardTarget

/--
The hub residue `1` covers every smooth non-hub target as soon as the hub
itself is mature.
-/
theorem smoothFor_noHub_covered_by_hub
    {k m : Nat} {h : Prime} {a : ShiftedAssignment}
    (hsmooth : SmoothFor h m)
    (hnotHub : ¬ h.1 ∣ m)
    (hah : (a h : Nat) = 1)
    (hmature : k * h.1 ≤ m + 1) :
    ShiftedMatureCovers k m a :=
  controllerSemigroup_covered_by_hub
    (smoothFor_controllerSemigroup_of_not_dvd hsmooth hnotHub)
    hah hmature

/--
Field-level form: these two elementary hypotheses discharge
`CompletionData.smooth_noHub` verbatim.
-/
theorem completion_smoothNoHub_from_hub
    {k threshold : Nat} {h : Prime} {a : ShiftedAssignment}
    (hah : (a h : Nat) = 1)
    (hmature :
      ∀ m : Nat, threshold ≤ m → k * h.1 ≤ m + 1) :
    ∀ m : Nat, threshold ≤ m →
      SmoothFor h m → ¬ h.1 ∣ m →
      ShiftedMatureCovers k m a := by
  intro m hm hsmooth hnotHub
  exact smoothFor_noHub_covered_by_hub
    hsmooth hnotHub hah (hmature m hm)

/--
It is enough to verify hub maturity once at the beginning of the tail.
-/
theorem completion_smoothNoHub_from_threshold
    {k threshold : Nat} {h : Prime} {a : ShiftedAssignment}
    (hah : (a h : Nat) = 1)
    (hmatureAtThreshold : k * h.1 ≤ threshold + 1) :
    ∀ m : Nat, threshold ≤ m →
      SmoothFor h m → ¬ h.1 ∣ m →
      ShiftedMatureCovers k m a :=
  completion_smoothNoHub_from_hub hah (fun _ hm =>
    Nat.le_trans hmatureAtThreshold (Nat.add_le_add_right hm 1))

end Erdos279
